services:
  customerapi:
    platform: linux/amd64
    image: customerapi
    build:
      context: .
      dockerfile: CustomerService/CustomerAPI/Dockerfile
    environment:
      - EShopDbContextKey=${ESHOP_SQLSERVER_KEY}
    networks:
      - eshop-network
    ports:
      - '62122:80'
  
  orderapi:
    platform: linux/amd64
    image: orderapi
    build:
      context: .
      dockerfile: OrderService/OrderAPI/Dockerfile
    environment:
      - EShopDbContextKey=${ESHOP_SQLSERVER_KEY}
    networks:
      - eshop-network
    ports:
      - '62123:80'

networks:
  eshop-network:
    external: true
